#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
    update-alternatives --remove vi /usr/bin/vi
    update-alternatives --remove vim /usr/bin/vim
    update-alternatives --remove vimdiff /usr/bin/vimdiff
    ;;

  upgrade|failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac

exit 0
